### ISSUE TITLE
Strange behavior observed while executing long jobs in Halvade cluster, combiner job does not kickstart automatically 

### ISSUE THREAD

**Issue by shirshen12** [ddcap/halvade#3]
Hi Halvade Team,

We have observed a strange behavior, when executing long running jobs on a local Hadoop Cluster.
When we run jobs to analyse small files, we dont exit from the shell running runHalvade.py and hence the combiner job after the DNA job gets executed successfully.

E.g., When we ran a job to analyse a paired end sequence file:
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/DRR000/DRR000001/DRR000001_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/DRR000/DRR000001/DRR000001_2.fastq.gz

we did not terminate our shell session, since its a short running job analyzing just 423 MB in 20 minutes.
Please see pastie for run log of the job:
http://pastie.org/private/kkp2zhaji8l0zbzjskygeg

But when we ran a job to analyse a large single ended job, SRR1425229.fastq.gz, from ENA, it takes approximately 5 hours to analyse it and we cannot have an active shell session all the time. Hence we terminated the shell session. The DNA job ran successfully but the combine job never took over to merge the VCF files. We observed this with other long running jobs for analyzing large files, eg., SRR999665_1.fastq.gz and SRR999665_2.fastq.gz from 1000genomes project.
Please see pastie for this behaviour:
http://pastie.org/private/di0ljedggdjuv91s1o41aw

Can we have a fire-and-forget behavior where runHalvade.py exits after submitting the job to YARN successfully  and the combiner job automatically takes over merging VCF files. This behavior will also allow better integration with other tools to check job status and do post processing stuff like cluster termination among others.

**Comment by ddcap** [comment]
I updated the script so now it starts Halvade in the background and writes the stderr and stdout to halvade.stderr and halvade.stdout respectivally. It exits as soon as the job has started, this also means that if the Halvade tasks isn't started because the output directory already existing for example than it will show this in the halvade.stderr log.
Let me know if it works, just replacing the runHalvade.py file with the new one should work. I always used a screen session before where I let the command run, so I can detach from the session and still monitor processes, but it makes sense to have it run in the background like this.

**Comment by shirshen12** [comment]
thanks for the fix, will test it on Friday. Will spawn the cluster again and report back to you. Sorry for the delay in response.

**Comment by shirshen12** [comment]
I have tested your fix with the DRR000001 paired end file set and it works :+1: Will test it with the other two files for coverage and report to u by EoD

**Comment by shirshen12** [comment]
Tested the sample: SRR999665_1.fastq.gz and SRR999665_2.fastq.gz and the fix works :+1: , got a merged vcf file of 267MB size. Testing a single ended file, if that succeeds, I will close the issue.

**Comment by shirshen12** [comment]
Tested the sample, SRR1425229.fastq.gz and the fix works :+1: Closing this issue.
